name: Hello World
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "A  demo buid"
  test:
    runs-on: ubuntu-latest
    need: build
    steps:
      - name : Test Phase
        run: echo "Running Test cases"
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy app
        run: echo "Deploying app"
